// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJkwSrjCBF6_S7Su1L6AUUaj2xEQ8UB4',
    appId: '1:736393182026:android:aac08f9a59c73d122adfb3',
    messagingSenderId: '736393182026',
    projectId: 'sales-tracking-d8667',
    storageBucket: 'sales-tracking-d8667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjS6H-Dm2LQ6qULhuZPOF56trFNswer8',
    appId: '1:736393182026:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '736393182026',
    projectId: 'sales-tracking-d8667',
    storageBucket: 'sales-tracking-d8667.firebasestorage.app',
    iosBundleId: 'com.example.salesTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwjS6H-Dm2LQ6qULhuZPOF56trFNswer8',
    appId: '1:736393182026:windows:a1b2c3d4e5f6g7h8',
    messagingSenderId: '736393182026',
    projectId: 'sales-tracking-d8667',
    authDomain: 'sales-tracking-d8667.firebaseapp.com',
    storageBucket: 'sales-tracking-d8667.firebasestorage.app',
  );
}
